const actionTypes = {
  // User
  USER_LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
  USER_LOGIN_FAIL: "USER_LOGIN_FAIL",
  USER_LOGOUT: "USER_LOGOUT",
  USER_GET_ALL_SUCCESS: "USER_GET_ALL_SUCCESS",
  USER_GET_SUCCESS: "USER_GET_SUCCESS",
  TEST_TANG: "TEST_TANG",
  TEST_GIAM: "TEST_GIAM",

  // JOB
  GET_JOB_SUCCESS: "GET_JOB_SUCCESS",
  GET_JOB_BY_ID_SUCCESS: "GET_JOB_BY_ID_SUCCESS",
  GET_MY_JOB_SUCCESS: "GET_MY_JOB_SUCCESS",
  GET_MY_JOB_APP_SUCCESS: "GET_MY_JOB_APP_SUCCESS",

  // Offer
  GET_MY_OFFER_SUCCESS: "GET_MY_OFFER_SUCCESS",
  GET_OFFER_BY_JOB_SUCCESS: "GET_OFFER_BY_JOB_SUCCESS",
};

export default actionTypes;
